Refactor Change HTTP Library
lucassm02/nodejs-template pull request #25
Opened 2024-03-21 19:53 UTC by gjovs

#### Description
This pull request to implement a transition from Express to Fastify, along with the addition of test suites and the reimplementation of adapters. This change aims to enhance performance, scalability, and overall stability of our platform.

#### What type of PR contains? 

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🔥 Performance Improvements
- [x] 🧑‍💻 Code Refactor
- [x] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

2024-04-15 16:05 UTC, lucassm02 requested changes
@gjovs congratulations on the implementation! I believe it must have been a huge challenge. Please check my comments so that we can proceed with the approval of this PR.

2024-04-15 16:21 UTC, gjovs commented on src/presentation/middlewares/token/validate-token-middleware.ts
> +      if (!authorization) return unauthorized('FICA FRIO AI MEU CHAPA');
For sure, fell sorry for that, I was really happy testing the fastify! 😁

2024-04-15 16:38 UTC, gjovs commented on src/infra/http/utils/http-server/http-server.ts
> +    ...args: RouteMiddleware[] | Function[]
It's a mistake, In some scenarios I was trying to save the data of routes to cut some parts of the process when reload.

2024-04-15 16:39 UTC, gjovs commented on src/infra/http/utils/http-server/http-server.ts
> +    this.paths.push(path);
It's a mistake, In some scenarios I was trying to save the data of routes to cut some parts of the process when reload.

2024-04-15 17:31 UTC, gjovs commented on src/infra/http/utils/http-server/http-server.ts
> -    if (middlewares.length) {
The middlewares wasn't being injected  right there, the implementation it's only looking to the default function imported, I'm fixing that

2024-04-16 19:55 UTC, lucassm02 approved these changes
@gjovs thank you for the implementation. This change will greatly improve the capacity and performance of our web server!😄

2024-04-16 19:55 UTC, merged