Create tests
lucassm02/nodejs-template pull request #30
Opened 2024-04-09 14:27 UTC by ItaloG

Description
This pull request implements tests on usecases, presentations, utils and other functions. I've refactor some inpropert dependencies injection and add TODO comments to codes i'm not aware of.

What type of PR contains?
- [ ] 🍕 Feature
- [ ]  🐛 Bug Fix
- [ ]  📝 Documentation Update
- [ ]  🔥 Performance Improvements
- [X]  🧑‍💻 Code Refactor
- [X]  ✅ Test
- [ ]  🤖 Build
- [ ]  🔁 CI
- [ ]  📦 Chore (Release)
- [ ]  ⏩ Revert

2024-04-15 13:49 UTC, lucassm02 commented
@ItaloG , please resolve the conflicts so that I can proceed with the review.

2024-04-15 14:53 UTC, ItaloG commented
@lucassm02 , I've resolved the conflicts.

2024-04-15 20:00 UTC, lucassm02 requested changes
I hope I've answered some of your questions. Thank you for adding those `TODOs`; it contributes a lot to the project's quality. I'll address them soon. Please just verify my request for file deletion.

2024-04-15 20:00 UTC, lucassm02 commented on test/integration/infra/worker/worker-manager.spec.ts
If the implementation is not correct, please remove the file

2024-04-15 20:00 UTC, lucassm02 commented on src/util/object/formatters/recursive-data-converter.ts
>    if (!object) return object;
This is just a validation at the implementation level; null or undefined should be passed as arguments.

2024-04-15 20:00 UTC, lucassm02 commented on src/util/object/formatters/recursive-data-converter.ts
> +      // TODO: this condition is correct? This should get instanceof item or data?
The validation is correct; it's to prevent objects of type `Date` from being modified

2024-04-16 17:31 UTC, ItaloG commented
The changes have been added

2024-04-16 18:34 UTC, lucassm02 approved these changes
@ItaloG thank you for the implementation. It's of great importance to the project, and it will greatly assist with the new implementations!

2024-04-16 18:35 UTC, merged